In [1]:
import numpy as np
import pandas as pd

In [12]:
PRESTITO = 200_000
ANNI = 30
TAN = 0.03

In [33]:
# Ammortamento all'italiana
numero_rate = ANNI * 12
quota_capitale = round(PRESTITO / numero_rate, 2)

quote_capitale = [0]
quote_interessi = [0]
capitale_residuo = [PRESTITO]

for i in range(numero_rate):
    quote_interessi.append(round(capitale_residuo[i] * TAN / 12, 2))
    capitale_residuo.append(capitale_residuo[-1] - quota_capitale)
    quote_capitale.append(quota_capitale)

quote_capitale[-1] = capitale_residuo[-2]
capitale_residuo[-1] = 0
    

df = pd.DataFrame({
    'quote_capitale': quote_capitale,
    'quote_interessi': quote_interessi,
    'capitale_residuo': capitale_residuo
})
df['rate'] = df['quote_capitale'] + df['quote_interessi']
#df['capitale_residuo'] = (PRESTITO - df['quote_capitale'].cumsum()).round()

In [34]:
display(df.head())
display(df.tail())

   quote_capitale  quote_interessi  capitale_residuo     rate
0            0.00             0.00         200000.00     0.00
1          555.56           500.00         199444.44  1055.56
2          555.56           498.61         198888.88  1054.17
3          555.56           497.22         198333.32  1052.78
4          555.56           495.83         197777.76  1051.39

     quote_capitale  quote_interessi  capitale_residuo    rate
356          555.56             6.94           2220.64  562.50
357          555.56             5.55           1665.08  561.11
358          555.56             4.16           1109.52  559.72
359          555.56             2.77            553.96  558.33
360          553.96             1.38              0.00  555.34

In [32]:
df.sum()

quote_capitale        200000.0
quote_interessi        90249.3
capitale_residuo    36099712.8
dtype: float64